HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/121.0.0.0 Safari/537.36"
}

PYTHON_TECHNOLOGIES = [
    "django",
    "flask",
    "fastapi",
    "pyramid",
    "javascript",
    "tornado",
    "bottle",
    "falcon",
    "http",
    "html/css",
    "css",
    "html",
    "iaas",
    "paas",
    "django rest framework",
    "graphQL",
    "rest",
    "gRPC",
    "WebSockets",
    "SOAP",
    "jinja2",
    "mako",
    "machine learning",
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "keras",
    "theano",
    "xgboost",
    "lightgmb",
    "catboost",
    "dask",
    "matplotlib",
    "seaborn",
    "plotly",
    "bokeh",
    "dash",
    "openai gym",
    "stable baselines",
    "docker",
    "kubernetes",
    "jenkins",
    "circleci",
    "ci/cd",
    "ansible",
    "chef",
    "puppet",
    "aws",
    "gcp",
    "microsoft azure",
    "heroku",
    "digitalocean",
    "openstack",
    "terraform",
    "postgresql",
    "mysql",
    "sqlite",
    "mariadb",
    "sqlalchemy",
    "mongodb",
    "cassandra",
    "redis",
    "couchdb",
    "dynamodb",
    "elasticsearch",
    "firebase realtime database",
    "pytest",
    "unittest",
    "nose",
    "hypothesis",
    "tox",
    "mock",
    "apache bench",
    "pylint",
    "flake8",
    "black",
    "isort",
    "mypy",
    "requests",
    "urllib",
    "httpx",
    "aiohttp",
    "twisted",
    "paramiko",
    "pyzmq",
    "websockets",
    "celery",
    "django-q",
    "apscheduler",
    "huey",
    "cron",
    "cryptography",
    "pycryptodome",
    "bcrypt",
    "hashids",
    "paramiko",
    "pyjwt",
    "oauth",
    "openid connect",
    "authlib",
    "jwt",
    "asyncio",
    "aiohttp",
    "asyncpg",
    "aiomysql",
    "aioredis",
    "quart",
    "beautifulsoup",
    "scrapy",
    "selenium",
    "lxml",
    "requests-html",
    "argparse",
    "click",
    "typer",
    "git",
    "github",
    "gitLab",
    "bitbucket",
    "trello",
    "jira",
    "asana",
    "slack",
    "sphinx",
    "jupyter notebooks",
    "poetry",
    "pipenv",
    "virtualenv",
    "docker compose",
    "pillow"
]
